---
title: "Data Wrangling"
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

## Data Wrangling

```{r, echo=FALSE}    
library(tidyverse)
library(lubridate)
```


```{r, echo=FALSE}    

deaths_df <- read.csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv"),check.names = FALSE)

# I dont know how to get the last column after I converted to a tibble
# I need this later in pivot_longer()
last_column <- colnames(deaths_df)[ncol(deaths_df)]

deaths <- as_tibble(deaths_df)

### Selecting

deaths <- select(deaths,-UID,-iso2,-iso3,-code3,-FIPS,-Country_Region,-Lat,-Long_,-Combined_Key)

### Rename column names

deaths <- rename(deaths,county=Admin2,state=Province_State,population=Population)

### Pivoting the whole table

deaths_pivoted <- pivot_longer(deaths,c(`1/22/20`:all_of(last_column)),names_to="date",values_to="deaths")
```
### Exercise: Plot states and counties
```{r}
### Filter and pivot counties

deaths_counties <- filter(deaths, !(county=="") & !(county=="Unassigned") & !grepl("Out of",county))
deaths_counties_pivoted <- pivot_longer(deaths_counties,c(`1/22/20`:all_of(last_column)),names_to="date",values_to="deaths")
deaths_counties_pivoted <- mutate(deaths_counties_pivoted,date=mdy(date))
deaths_counties_pivoted <- mutate(deaths_counties_pivoted,county_state=paste(county,state))
deaths_counties_pivoted <- drop_na(deaths_counties_pivoted)
deaths_counties_pivoted <- mutate(deaths_counties_pivoted,deaths_per_million=as.numeric(deaths)*as.numeric(population)/1000000)

### Summarise deaths by date

deaths_counties_pivoted %>%
subset(date > as.Date("2020-03-01")) %>%
top_n(100) %>%
ggplot() + geom_line(mapping = aes(x = date, y = deaths_per_million,color=county_state)) 
```
